version: "5.1.0"
services:
  node-app:
    container_name: ezz
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - auth_token=0102201010
      # you can pass the env file directly using and what is in environment overrides what is in file
    env_file:
      - ./.env


      # docker compose order
      
#  Dockerfile ENV number=1        → container gets number=1
#            ↓
#   env_file: number=2             → overwrites, container now has number=2
#            ↓
#   environment: number=3          → overwrites, container now has number=3
#            ↓
#   shell: docker compose run -e number=4 → overwrites, container now has number=4

#   Final value inside the container: 4
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - dataDir:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

volumes:
  dataDir:
  