# it is a file to run my application representing an empty machine
# the start is always from the base image
# use words like slim and alpine to reduce the spaces of node used in image
FROM node:22.13.0-alpine
# now the node js with the specified version will be installed in the container
# you need to create a folder to put your files in, files needed for proj to work
# such as the package.json, files autogenerated from scripts with env based and so on
ARG PORT=5000
ENV PORT=${PORT}

WORKDIR /app
# then move your needed files to the container 
COPY package.json .
# then run the commands you need like install commands
RUN npm install
# this is to copy all the files except of those in the docker ignore
COPY . .
# copy all of your project file but use dockerignore file to avoid moving unneeded files


EXPOSE ${PORT}

CMD ["npm","run", "dev"]